(part "SQ2318AES-T1_BE3"
    (packageRef "SOT95P237X112-3N")
    (interface
        (port "1" (symbPinId 1) (portName "G") (portType INOUT))
        (port "2" (symbPinId 2) (portName "S") (portType INOUT))
        (port "3" (symbPinId 3) (portName "D") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Mouser_Part_Number" "78-SQ2318AES-T1_BE3")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Vishay-Siliconix/SQ2318AES-T1_BE3?qs=TiOZkKH1s2QuMGPo0iDprw%3D%3D")
    (property "Manufacturer_Name" "Vishay")
    (property "Manufacturer_Part_Number" "SQ2318AES-T1_BE3")
    (property "Description" "MOSFET N-CHANNEL 40V (D-S)")
    (property "Datasheet_Link" "https://www.mouser.co.uk/datasheet/2/427/sq2318aes-1764491.pdf")
    (property "symbolName1" "SQ2318AES-T1_BE3")
)
