(part "87833-0419"
    (packageRef "SHDRRA4W55P200_2X2_665X640X630P")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "3") (portType INOUT))
        (port "4" (symbPinId 4) (portName "4") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "181")
    (property "Mouser_Part_Number" "538-87833-0419")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Molex/87833-0419?qs=Vr3ZXvgdfhbIBPo%252BhQCZsA%3D%3D")
    (property "Manufacturer_Name" "Molex")
    (property "Manufacturer_Part_Number" "87833-0419")
    (property "Description" "Headers & Wire Housings MGrid Hdr Shrd RA /Stdf GFLF 4Ckt")
    (property "Datasheet_Link" "https://www.molex.com/pdm_docs/sd/878330419_sd.pdf")
    (property "symbolName1" "87833-0419")
)
