(part "ADP1610ARMZ-R7"
    (packageRef "SOP65P490X110-8N")
    (interface
        (port "1" (symbPinId 1) (portName "COMP") (portType INOUT))
        (port "2" (symbPinId 2) (portName "FB") (portType INOUT))
        (port "3" (symbPinId 3) (portName "%SD%") (portType INOUT))
        (port "4" (symbPinId 4) (portName "GND") (portType INOUT))
        (port "5" (symbPinId 5) (portName "SW") (portType INOUT))
        (port "6" (symbPinId 6) (portName "IN") (portType INOUT))
        (port "7" (symbPinId 7) (portName "RT") (portType INOUT))
        (port "8" (symbPinId 8) (portName "SS") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "584-ADP1610ARMZ-R7")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Analog-Devices/ADP1610ARMZ-R7?qs=WIvQP4zGanjTQwiTj85NkQ%3D%3D")
    (property "Manufacturer_Name" "Analog Devices")
    (property "Manufacturer_Part_Number" "ADP1610ARMZ-R7")
    (property "Description" "Switching Voltage Regulators 1.2 MHz PWM Boost Switching Regulator")
    (property "Datasheet_Link" "https://www.analog.com/media/en/technical-documentation/data-sheets/ADP1610.pdf")
    (property "symbolName1" "ADP1610ARMZ-R7")
)
