(part "FDC1004DGSR"
    (packageRef "SOP50P490X110-10N")
    (interface
        (port "1" (symbPinId 1) (portName "SHLD1") (portType INPUT))
        (port "2" (symbPinId 2) (portName "CIN1") (portType INPUT))
        (port "3" (symbPinId 3) (portName "CIN2") (portType INPUT))
        (port "4" (symbPinId 4) (portName "CIN3") (portType INPUT))
        (port "5" (symbPinId 5) (portName "CIN4") (portType INPUT))
        (port "6" (symbPinId 6) (portName "SHLD2") (portType INPUT))
        (port "7" (symbPinId 7) (portName "GND") (portType GROUND))
        (port "8" (symbPinId 8) (portName "VDD") (portType POWER))
        (port "9" (symbPinId 9) (portName "SCL") (portType INPUT))
        (port "10" (symbPinId 10) (portName "SDA") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "595-FDC1004DGSR")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Texas-Instruments/FDC1004DGSR?qs=zEQ6BYqA5vF%252BEdgfKNFEaA%3D%3D")
    (property "Manufacturer_Name" "Texas Instruments")
    (property "Manufacturer_Part_Number" "FDC1004DGSR")
    (property "Description" "4 Channel Capacitance to Digital Converter for Capacitive Sensing (Cap Sensing) Solutions")
    (property "Datasheet_Link" "http://www.ti.com/lit/gpn/fdc1004")
    (property "symbolName1" "FDC1004DGSR")
)
