(part "CSS-0575A-SMT-TR"
    (packageRef "CSS0575ASMTTR")
    (interface
        (port "1" (symbPinId 1) (portName "+") (portType INOUT))
        (port "2" (symbPinId 2) (portName "-") (portType INOUT))
        (port "3" (symbPinId 3) (portName "NC") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Mouser_Part_Number" "490-CSS-0575A-SMT-TR")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/CUI-Devices/CSS-0575A-SMT-TR?qs=WyjlAZoYn52WhHVOl0obVQ%3D%3D")
    (property "Manufacturer_Name" "Same Sky")
    (property "Manufacturer_Part_Number" "CSS-0575A-SMT-TR")
    (property "Description" "5 mm, 3 V, 76 dB, Surface Mount (SMT), Magnetic Audio Transducer Buzzer")
    (property "Datasheet_Link" "https://www.sameskydevices.com/product/resource/css-0575a-smt-tr.pdf")
    (property "symbolName1" "CSS-0575A-SMT-TR")
)
