(part "AD-85F4CR"
    (packageRef "AD85F4CR")
    (interface
        (port "1" (symbPinId 1) (portName "+") (portType INOUT))
        (port "2" (symbPinId 2) (portName "-") (portType INOUT))
        (port "3" (symbPinId 3) (portName "DUMMY") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Mouser_Part_Number" "")
    (property "Mouser_Price/Stock" "")
    (property "Manufacturer_Name" "AATC")
    (property "Manufacturer_Part_Number" "AD-85F4CR")
    (property "Description" "Piezo Buzzers & Audio Indicators EM Buzzer 2730Hz 3.6VAC, 87dBA")
    (property "Datasheet_Link" "https://www.aatc.tw/images/pdf/202005089c959.pdf")
    (property "symbolName1" "AD-85F4CR")
)
