(part "DMP2008UFG-7"
    (packageRef "DMTH8008LFGQ7")
    (interface
        (port "1" (symbPinId 1) (portName "S_1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "S_2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "S_3") (portType INOUT))
        (port "4" (symbPinId 4) (portName "G") (portType INOUT))
        (port "5" (symbPinId 5) (portName "D_1") (portType INOUT))
        (port "6" (symbPinId 6) (portName "D_2") (portType INOUT))
        (port "7" (symbPinId 7) (portName "D_3") (portType INOUT))
        (port "8" (symbPinId 8) (portName "D_4") (portType INOUT))
        (port "9" (symbPinId 9) (portName "D_5") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Mouser_Part_Number" "621-DMP2008UFG-7")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Diodes-Incorporated/DMP2008UFG-7?qs=wo71MgyKIyHArDy7nW0BNA%3D%3D")
    (property "Manufacturer_Name" "Diodes Incorporated")
    (property "Manufacturer_Part_Number" "DMP2008UFG-7")
    (property "Description" "Diodes Inc DMP2008UFG-7 P-channel MOSFET Transistor, 11 A, -20 V, 8-Pin POWERDI3333")
    (property "Datasheet_Link" "https://www.diodes.com//assets/Datasheets/DMP2008UFG.pdf")
    (property "symbolName1" "DMP2008UFG-7")
)
