(part "2920L600_24SLER"
    (packageRef "2920L700SLPR")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Mouser_Part_Number" "576-2920L600/24SLER")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Littelfuse/2920L600-24SLER?qs=7MVldsJ5Uaz%2FccYHZvZIZA%3D%3D")
    (property "Manufacturer_Name" "LITTELFUSE")
    (property "Manufacturer_Part_Number" "2920L600/24SLER")
    (property "Description" "Low Rho Surface Mount Resettable PTC Fuse")
    (property "Datasheet_Link" "https://www.mouser.fr/datasheet/2/240/littelfuse_ptc_low_rho_datasheet_pdf-1901322.pdf")
    (property "symbolName1" "2920L600_24SLER")
)
