(part "35312-0460"
    (packageRef "SHDR4W64P0X250_1X4_1246X650X700P")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "3") (portType INOUT))
        (port "4" (symbPinId 4) (portName "4") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "181")
    (property "Mouser_Part_Number" "538-35312-0460")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Molex/35312-0460?qs=K5bGVUuM57oIWvCwIBpyrQ%3D%3D")
    (property "Manufacturer_Name" "Molex")
    (property "Manufacturer_Part_Number" "35312-0460")
    (property "Description" "Headers & Wire Housings 2.5 PITCH W/B CONN WAFER ASSY")
    (property "Datasheet_Link" "https://www.molex.com/pdm_docs/sd/353120460_sd.pdf")
    (property "symbolName1" "35312-0460")
)
