(part "EEH-ZA1V680XP"
    (packageRef "EEHZA1E101XP")
    (interface
        (port "1" (symbPinId 1) (portName "+") (portType INOUT))
        (port "2" (symbPinId 2) (portName "-") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Mouser_Part_Number" "667-EEH-ZA1V680XP")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Panasonic/EEH-ZA1V680XP?qs=7UCyOFMWVHavYMOgLABudw%3D%3D")
    (property "Manufacturer_Name" "Panasonic")
    (property "Manufacturer_Part_Number" "EEH-ZA1V680XP")
    (property "Description" "Aluminum Organic Polymer Capacitors 68uF 35volt AEC-Q200")
    (property "Datasheet_Link" "http://industrial.panasonic.com/cdbs/www-data/pdf/RDD0000/ABA0000C1221.pdf")
    (property "symbolName1" "EEH-ZA1V680XP")
)
