(part "ADP162AUJZ-3_3-R7"
    (packageRef "SOT95P280X100-5N")
    (interface
        (port "1" (symbPinId 1) (portName "VIN") (portType INOUT))
        (port "2" (symbPinId 2) (portName "GND") (portType INOUT))
        (port "3" (symbPinId 3) (portName "EN") (portType INOUT))
        (port "4" (symbPinId 4) (portName "NC") (portType INOUT))
        (port "5" (symbPinId 5) (portName "VOUT") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "584-ADP162AUJZ-3.3R7")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Analog-Devices/ADP162AUJZ-3.3-R7?qs=WIvQP4zGangHoc9MX39OnA%3D%3D")
    (property "Manufacturer_Name" "Analog Devices")
    (property "Manufacturer_Part_Number" "ADP162AUJZ-3.3-R7")
    (property "Description" "LDO Voltage Regulators 150mA LDO 3.3Vout")
    (property "Datasheet_Link" "https://www.analog.com/media/en/technical-documentation/data-sheets/ADP160_161_162_163.pdf")
    (property "symbolName1" "ADP162AUJZ-3_3-R7")
)
