(part "SS34"
    (packageRef "DIOM8059X256N")
    (interface
        (port "1" (symbPinId 1) (portName "K") (portType INOUT))
        (port "2" (symbPinId 2) (portName "A") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Mouser_Part_Number" "512-SS34")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/onsemi-Fairchild/SS34?qs=2ONuHmP%2FXzb3ub11UdFfdQ%3D%3D")
    (property "Manufacturer_Name" "onsemi")
    (property "Manufacturer_Part_Number" "SS34")
    (property "Description" "Low-Forward Voltage Drop; Metal to Silicon Rectifiers, Majority Carrier Conduction; High-Surge Current Capability; Easy Pick and Place")
    (property "Datasheet_Link" "https://www.onsemi.com/pub/Collateral/SS39-D.PDF")
    (property "symbolName1" "SS34")
)
