(part "LQH3NPN4R7MMEL"
    (packageRef "LQH3NPN100MMEL")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "33")
    (property "Mouser_Part_Number" "81-LQH3NPN4R7MMEL")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Murata-Electronics/LQH3NPN4R7MMEL?qs=sJ5gq5MLFXqkg2Q4z1mYdA%3D%3D")
    (property "Manufacturer_Name" "Murata Electronics")
    (property "Manufacturer_Part_Number" "LQH3NPN4R7MMEL")
    (property "Description" "LQH3NPN_ME Series Inductor 4.7uH +/-20% 1212 (3030)")
    (property "Datasheet_Link" "https://search.murata.co.jp/Ceramy/image/img/P02/JELF243A-0153.pdf")
    (property "symbolName1" "LQH3NPN4R7MMEL")
)
