(part "PESD3V3NW-SFYL"
    (packageRef "PMEG3005AESFYL")
    (interface
        (port "1" (symbPinId 1) (portName "K1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "K2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Mouser_Part_Number" "771-PESD3V3NW-SFYL")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Nexperia/PESD3V3NW-SFYL?qs=P1JMDcb91o7V%252BTs8TRh1Ig%3D%3D")
    (property "Manufacturer_Name" "Nexperia")
    (property "Manufacturer_Part_Number" "PESD3V3NW-SFYL")
    (property "Description" "PESD3V3NW-SF - Extremely low capacitance bidirectional ESD protection@en-us")
    (property "Datasheet_Link" "https://assets.nexperia.com/documents/data-sheet/PESD3V3NW-SF.pdf")
    (property "symbolName1" "PESD3V3NW-SFYL")
)
