(part "MAX680CSA+"
    (packageRef "SOIC127P600X175-8N")
    (interface
        (port "1" (symbPinId 1) (portName "C1-") (portType INOUT))
        (port "2" (symbPinId 2) (portName "C2+") (portType INOUT))
        (port "3" (symbPinId 3) (portName "C2-") (portType INOUT))
        (port "4" (symbPinId 4) (portName "V-") (portType INOUT))
        (port "5" (symbPinId 5) (portName "GND") (portType INOUT))
        (port "6" (symbPinId 6) (portName "VCC") (portType INOUT))
        (port "7" (symbPinId 7) (portName "C1+") (portType INOUT))
        (port "8" (symbPinId 8) (portName "V+") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "700-MAX680CSA")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Analog-Devices-Maxim-Integrated/MAX680CSA%2b?qs=1THa7WoU59GmJru%252B3pd8uQ%3D%3D")
    (property "Manufacturer_Name" "Analog Devices")
    (property "Manufacturer_Part_Number" "MAX680CSA+")
    (property "Description" "Charge Pump INV/STPUP  10V 10mA")
    (property "Datasheet_Link" "https://datasheet.datasheetarchive.com/originals/distributors/Datasheets-18/DSA-340121.pdf")
    (property "symbolName1" "MAX680CSA+")
)
