(part "INA228AIDGSR"
    (packageRef "SOP50P490X110-10N")
    (interface
        (port "1" (symbPinId 1) (portName "A1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "A0") (portType INOUT))
        (port "3" (symbPinId 3) (portName "ALERT") (portType INOUT))
        (port "4" (symbPinId 4) (portName "SDA") (portType INOUT))
        (port "5" (symbPinId 5) (portName "SCL") (portType INOUT))
        (port "6" (symbPinId 6) (portName "VS") (portType INOUT))
        (port "7" (symbPinId 7) (portName "GND") (portType INOUT))
        (port "8" (symbPinId 8) (portName "VBUS") (portType INOUT))
        (port "9" (symbPinId 9) (portName "IN-") (portType INOUT))
        (port "10" (symbPinId 10) (portName "IN+") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "595-INA228AIDGSR")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Texas-Instruments/INA228AIDGSR?qs=pUKx8fyJudB2qGvt%252BmXPAg%3D%3D")
    (property "Manufacturer_Name" "Texas Instruments")
    (property "Manufacturer_Part_Number" "INA228AIDGSR")
    (property "Description" "Current & Power Monitors & Regulators 85-V, 20-bit, ultra-precise, I2C output current/voltage/power/energy/charge monitor with alert</p")
    (property "Datasheet_Link" "https://www.ti.com/general/docs/suppproductinfo.tsp?distId=10&gotoUrl=http%3A%2F%2Fwww.ti.com%2Flit%2Fgpn%2Fina228")
    (property "symbolName1" "INA228AIDGSR")
)
