(part "MIC94060YMT-TR"
    (packageRef "SON50P160X120X60-5N-D")
    (interface
        (port "1" (symbPinId 1) (portName "VOUT") (portType INOUT))
        (port "2" (symbPinId 2) (portName "GND_1") (portType INOUT))
        (port "3" (symbPinId 3) (portName "VIN") (portType INOUT))
        (port "4" (symbPinId 4) (portName "EN") (portType INOUT))
        (port "5" (symbPinId 5) (portName "GND_2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "998-MIC94060YMTTR")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Microchip-Technology-Atmel/MIC94060YMT-TR?qs=Y3Q3JoKAO1SQS%2F%2FiEDCB1w%3D%3D")
    (property "Manufacturer_Name" "Microchip")
    (property "Manufacturer_Part_Number" "MIC94060YMT-TR")
    (property "Description" "Power Switch ICs - Power Distribution Loadswitch w/level-shift")
    (property "Datasheet_Link" "http://www.microchip.com/mymicrochip/filehandler.aspx?ddocname=en580310")
    (property "symbolName1" "MIC94060YMT-TR")
)
