(part "SMTU2032-LF"
    (packageRef "SMTU2032LF")
    (interface
        (port "1" (symbPinId 1) (portName "+") (portType INOUT))
        (port "2" (symbPinId 2) (portName "-") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Mouser_Part_Number" "614-SMTU2032-LF")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Renata/SMTU2032-LF?qs=r1PAtlylphCLeXbokB9Tog%3D%3D")
    (property "Manufacturer_Name" "RENATA")
    (property "Manufacturer_Part_Number" "SMTU2032-LF")
    (property "Description" "Coin Cell Battery Holders SFC MNT FOR CR2032")
    (property "Datasheet_Link" "https://componentsearchengine.com/Datasheets/1/SMTU2032-LF.pdf")
    (property "symbolName1" "SMTU2032-LF")
)
