(part "ISL8490EIBZ-T"
    (packageRef "SOIC127P600X175-8N")
    (interface
        (port "1" (symbPinId 1) (portName "VCC") (portType INOUT))
        (port "2" (symbPinId 2) (portName "RO") (portType INOUT))
        (port "3" (symbPinId 3) (portName "DI") (portType INOUT))
        (port "4" (symbPinId 4) (portName "GND") (portType INOUT))
        (port "5" (symbPinId 5) (portName "Y") (portType INOUT))
        (port "6" (symbPinId 6) (portName "Z") (portType INOUT))
        (port "7" (symbPinId 7) (portName "B") (portType INOUT))
        (port "8" (symbPinId 8) (portName "A") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "968-ISL8490EIBZ-T")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Renesas-Intersil/ISL8490EIBZ-T/?qs=dAsayXGOMruV4w9kYM7q7w%3D%3D")
    (property "Manufacturer_Name" "Renesas Electronics")
    (property "Manufacturer_Part_Number" "ISL8490EIBZ-T")
    (property "Description" "The ISL8488E, ISL8489E, ISL8490E, ISL8491E devices are ESD protected, BiCMOS, 5V powered, single transceivers that meet both the RS-485 and RS-422 standards for balanced communication. Each driver output and receiver input is protected against +/-15kV ESD strikes, without latch-up. Unlike competitive versions, these Intersil devices are specified for 10% tolerance supplies (4. 5V to 5. 5V). These devices are configured for full duplex (separate Rx input and Tx output pins) applications, so they are ideal for ")
    (property "Datasheet_Link" "https://www.renesas.com/en-us/www/doc/datasheet/isl8488e-89e-90e-91e.pdf")
    (property "symbolName1" "ISL8490EIBZ-T")
)
