(part "PTVS30VS1UR_115"
    (packageRef "SOD123W")
    (interface
        (port "1" (symbPinId 1) (portName "K") (portType INOUT))
        (port "2" (symbPinId 2) (portName "A") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Mouser_Part_Number" "771-PTVS30VS1UR115")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Nexperia/PTVS30VS1UR115?qs=GcY6OjH1zdkc%252BCtbt7xiQQ%3D%3D")
    (property "Manufacturer_Name" "Nexperia")
    (property "Manufacturer_Part_Number" "PTVS30VS1UR,115")
    (property "Description" "TVS Diodes - Transient Voltage Suppressors TVS UNI-DIR 30V 400W")
    (property "Datasheet_Link" "https://assets.nexperia.com/documents/data-sheet/PTVSXS1UR_SER.pdf")
    (property "symbolName1" "PTVS30VS1UR_115")
)
