(part "39-30-1040"
    (packageRef "39-30-104Y")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "3") (portType INOUT))
        (port "4" (symbPinId 4) (portName "4") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "181")
    (property "Mouser_Part_Number" "538-39-30-1040")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Molex/39-30-1040?qs=tRPrwvvr%2FugKtPXHFlZTbg%3D%3D")
    (property "Manufacturer_Name" "Molex")
    (property "Manufacturer_Part_Number" "39-30-1040")
    (property "Description" "Mini-Fit Jr. Header, Dual Row, Right-Angle, with Snap-in Plastic Peg PCB Lock, 4 Circuits, PA Polyamide Nylon 6/6 94V-0")
    (property "Datasheet_Link" "https://www.molex.com/pdm_docs/sd/039300020_sd.pdf")
    (property "symbolName1" "39-30-1040")
)
