(part "MCP602-E_SN"
    (packageRef "SOIC127P600X175-8N")
    (interface
        (port "1" (symbPinId 1) (portName "VOUTA") (portType INOUT))
        (port "2" (symbPinId 2) (portName "VINA–") (portType INOUT))
        (port "3" (symbPinId 3) (portName "VINA+") (portType INOUT))
        (port "4" (symbPinId 4) (portName "VSS") (portType INOUT))
        (port "5" (symbPinId 5) (portName "VINB+") (portType INOUT))
        (port "6" (symbPinId 6) (portName "VINB–") (portType INOUT))
        (port "7" (symbPinId 7) (portName "VOUTB") (portType INOUT))
        (port "8" (symbPinId 8) (portName "VDD") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "579-MCP602-E/SN")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Microchip-Technology/MCP602-E-SN?qs=iRhCjdSJZe6hCMMETMefXQ%3D%3D")
    (property "Manufacturer_Name" "Microchip")
    (property "Manufacturer_Part_Number" "MCP602-E/SN")
    (property "Description" "Microchip MCP602-E/SN, Dual Op Amp, 2.8MHz Rail-Rail, 2.7  6 V, 8-Pin SOIC")
    (property "Datasheet_Link" "https://www.mouser.in/datasheet/2/268/21314g-2449592.pdf")
    (property "symbolName1" "MCP602-E_SN")
)
