(part "PA2248_153NLT"
    (packageRef "INDPM155165X1300N")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "33")
    (property "Mouser_Part_Number" "673-PA2248.153NLT")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Pulse-Electronics/PA2248.153NLT?qs=vLWxofP3U2yRehsl8tescA%3D%3D")
    (property "Manufacturer_Name" "YAGEO")
    (property "Manufacturer_Part_Number" "PA2248.153NLT")
    (property "Description" "FIXED IND 15UH 22A 7.5MOHM SMD")
    (property "Datasheet_Link" "https://www.mouser.de/datasheet/2/336/P865-1771766.pdf")
    (property "symbolName1" "PA2248_153NLT")
)
