M48
; DRILL file {KiCad 9.0.7} date 2026-02-18T02:14:19+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-02-18T02:14:19+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.100
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.850
%
G90
G05
T1
X184.5Y-124.0
X187.5Y-124.0
T2
X148.3Y-119.0
X152.7Y-119.0
X171.3Y-119.0
X175.7Y-119.0
T3
X134.88Y-48.75
X183.14Y-48.75
M30
