(part "108"
    (packageRef "108")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Mouser_Part_Number" "534-108")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Keystone-Electronics/108?qs=Q3RoVmURDomBWyH0dBAK9w%3D%3D")
    (property "Manufacturer_Name" "Keystone Electronics")
    (property "Manufacturer_Part_Number" "108")
    (property "Description" "Cylindrical Battery Contacts, Clips, Holders & Springs Battery HOLDER PC 1/2 AA")
    (property "Datasheet_Link" "https://www.mouser.se/datasheet/2/215/108-745412.pdf")
    (property "symbolName1" "108")
)
