(part "DM3AT-SF-PEJM5_41_"
    (packageRef "DM3ATSFPEJM541")
    (interface
        (port "1" (symbPinId 1) (portName "DAT2") (portType INOUT))
        (port "2" (symbPinId 2) (portName "CD/DAT3") (portType INOUT))
        (port "3" (symbPinId 3) (portName "CMD") (portType INOUT))
        (port "4" (symbPinId 4) (portName "VDD") (portType INOUT))
        (port "5" (symbPinId 5) (portName "CLK") (portType INOUT))
        (port "6" (symbPinId 6) (portName "VSS") (portType INOUT))
        (port "7" (symbPinId 7) (portName "DAT0") (portType INOUT))
        (port "8" (symbPinId 8) (portName "DAT1") (portType INOUT))
        (port "MP1" (symbPinId 9) (portName "MP1") (portType INOUT))
        (port "MP2" (symbPinId 10) (portName "MP2") (portType INOUT))
        (port "MP3" (symbPinId 11) (portName "MP3") (portType INOUT))
        (port "MP4" (symbPinId 12) (portName "MP4") (portType INOUT))
        (port "MP5" (symbPinId 13) (portName "MP5") (portType INOUT))
        (port "MP6" (symbPinId 14) (portName "MP6") (portType INOUT))
        (port "MP7" (symbPinId 15) (portName "MP7") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "181")
    (property "Mouser_Part_Number" "798-DM3ATSFPEJM541")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Hirose-Connector/DM3AT-SF-PEJM541?qs=iyLo5FA4poAlFf1J7h9Amg%3D%3D")
    (property "Manufacturer_Name" "Hirose")
    (property "Manufacturer_Part_Number" "DM3AT-SF-PEJM5(41)")
    (property "Description" "Memory Card Connectors SD R/A PUSH-PUSH SMD CONN MICRO")
    (property "Datasheet_Link" "https://www.hirose.com/en/product/document?clcode=CL0609-0031-0-00&productname=DM3AT-SF-PEJM5&series=DM3&documenttype=2DDrawing&lang=en&documentid=0000947170")
    (property "symbolName1" "DM3AT-SF-PEJM5_41_")
)
