(part "MCP1642D-50I_MS"
    (packageRef "SOP65P490X110-8N")
    (interface
        (port "1" (symbPinId 1) (portName "EN") (portType INOUT))
        (port "2" (symbPinId 2) (portName "NC") (portType INOUT))
        (port "3" (symbPinId 3) (portName "PG") (portType INOUT))
        (port "4" (symbPinId 4) (portName "VOUT") (portType INOUT))
        (port "5" (symbPinId 5) (portName "SW") (portType INOUT))
        (port "6" (symbPinId 6) (portName "PGND") (portType INOUT))
        (port "7" (symbPinId 7) (portName "SGND") (portType INOUT))
        (port "8" (symbPinId 8) (portName "VIN") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "579-MCP1642D-50I/MS")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Microchip-Technology-Atmel/MCP1642D-50I-MS?qs=kUzwwg2uGjVoXH8JFWZOdQ%3D%3D")
    (property "Manufacturer_Name" "Microchip")
    (property "Manufacturer_Part_Number" "MCP1642D-50I/MS")
    (property "Description" "Switching Voltage Regulators Step-up DC/DC Reg 1 MHz, 1.6A, 5Vout")
    (property "Datasheet_Link" "http://www.microchip.com/mymicrochip/filehandler.aspx?ddocname=en572899")
    (property "symbolName1" "MCP1642D-50I_MS")
)
