(part "LT3960EMSE_TRPBF"
    (packageRef "SOP50P490X110-11N")
    (interface
        (port "1" (symbPinId 1) (portName "CANSDAL") (portType INOUT))
        (port "2" (symbPinId 2) (portName "CANSDAH") (portType INOUT))
        (port "3" (symbPinId 3) (portName "GND_1") (portType INOUT))
        (port "4" (symbPinId 4) (portName "CANSCLH") (portType INOUT))
        (port "5" (symbPinId 5) (portName "CANSCLL") (portType INOUT))
        (port "6" (symbPinId 6) (portName "VIN") (portType INOUT))
        (port "7" (symbPinId 7) (portName "EN/MODE") (portType INOUT))
        (port "8" (symbPinId 8) (portName "VCC") (portType INOUT))
        (port "9" (symbPinId 9) (portName "SCL") (portType INOUT))
        (port "10" (symbPinId 10) (portName "SDA") (portType INOUT))
        (port "11" (symbPinId 11) (portName "GND_2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "584-LT3960EMSE#TRPBF")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Analog-Devices/LT3960EMSETRPBF?qs=T94vaHKWudSYrMnOgEOV%252BA%3D%3D")
    (property "Manufacturer_Name" "Analog Devices")
    (property "Manufacturer_Part_Number" "LT3960EMSE#TRPBF")
    (property "Description" "n Protected from Overvoltage Line Faults to +/-40V n Up to 400kbps I2C Communications n 4V to 60V Power Supply Range with Internal 3.3V Regulator n 3.3V or 5V Bus Voltage n Extended Common Mode Range (+/-36V) n Current Limited Drivers with Thermal Shutdown n Power-Up/Down Glitch Free Driver Outputs n Low Current Shutdown Mode n Transmit Data Dominant Timeout Function n E- and J-Grades Available n Available in a 10-Lead MSOP Package n AEC-Q100 Qualified for Automotive Applications")
    (property "Datasheet_Link" "https://www.analog.com/LT3960/datasheet")
    (property "symbolName1" "LT3960EMSE_TRPBF")
)
