(part "SRP7030CA-4R7M"
    (packageRef "SRP7030CA2R2M")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "652-SRP7030CA-4R7M")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Bourns/SRP7030CA-4R7M?qs=PzGy0jfpSMvKDOfDezgaiA%3D%3D")
    (property "Manufacturer_Name" "Bourns")
    (property "Manufacturer_Part_Number" "SRP7030CA-4R7M")
    (property "Description" "Fixed Inductors Ind,7.8x7.6x2.9mm,4.7uH 20%,9A,Shd,SMD")
    (property "Datasheet_Link" "https://componentsearchengine.com/Datasheets/1/SRP7030CA-4R7M.pdf")
    (property "symbolName1" "SRP7030CA-4R7M")
)
