(part "EPG_0B_304_HLN"
    (packageRef "EPG0B304HLN")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "3") (portType INOUT))
        (port "4" (symbPinId 4) (portName "4") (portType INOUT))
        (port "5" (symbPinId 5) (portName "GND_1") (portType INOUT))
        (port "6" (symbPinId 6) (portName "GND_2") (portType INOUT))
        (port "7" (symbPinId 7) (portName "GND_3") (portType INOUT))
        (port "8" (symbPinId 8) (portName "GND_4") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "181")
    (property "Mouser_Part_Number" "736-EPG0B304HLN")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/LEMO/EPG.0B.304.HLN?qs=Py8BJuJ8NHuk1oBwrlohFA%3D%3D")
    (property "Manufacturer_Name" "LEMO")
    (property "Manufacturer_Part_Number" "EPG.0B.304.HLN")
    (property "Description" "4 way size 0B PCB mount socket,7A Lemo 0B Series, 4 Pole Right Angle Through Hole Connector Socket, Shell Size 0, with Female Contacts")
    (property "Datasheet_Link" "https://web.lemo.com/img/resources/catalog/ROW/UK_English/unipole_multipole.pdf")
    (property "symbolName1" "EPG_0B_304_HLN")
)
