(part "107"
    (packageRef "107")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Mouser_Part_Number" "534-107")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Keystone-Electronics/107?qs=Q3RoVmURDolD5lQJEVRplg%3D%3D")
    (property "Manufacturer_Name" "Keystone Electronics")
    (property "Manufacturer_Part_Number" "107")
    (property "Description" "KEYSTONE - 107 - BATTERY HOLDER, 23MM COIN CELL, THROUGH HOLE")
    (property "Datasheet_Link" "https://componentsearchengine.com/Datasheets/2/107.pdf")
    (property "symbolName1" "107")
)
