(part "105314-2104"
    (packageRef "1053142104")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "3") (portType INOUT))
        (port "4" (symbPinId 4) (portName "4") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "181")
    (property "Mouser_Part_Number" "538-105314-2104")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Molex/105314-2104?qs=5aG0NVq1C4z8s50hNvpgCw%3D%3D")
    (property "Manufacturer_Name" "Molex")
    (property "Manufacturer_Part_Number" "105314-2104")
    (property "Description" "Headers & Wire Housings NANOFIT HDR RA DLR 4CKT TIN NAT")
    (property "Datasheet_Link" "https://componentsearchengine.com/Datasheets/1/105314-2104.pdf")
    (property "symbolName1" "105314-2104")
)
