(part "STL42P6LLF6"
    (packageRef "STL42P6LLF6")
    (interface
        (port "1" (symbPinId 1) (portName "S_1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "S_2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "S_3") (portType INOUT))
        (port "4" (symbPinId 4) (portName "G") (portType INOUT))
        (port "5" (symbPinId 5) (portName "D_1") (portType INOUT))
        (port "6" (symbPinId 6) (portName "D_2") (portType INOUT))
        (port "7" (symbPinId 7) (portName "D_3") (portType INOUT))
        (port "8" (symbPinId 8) (portName "D_4") (portType INOUT))
        (port "9" (symbPinId 9) (portName "D_5") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Mouser_Part_Number" "511-STL42P6LLF6")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/STMicroelectronics/STL42P6LLF6?qs=4b8myOmUP%252Bvt1KYehFRtBw%3D%3D")
    (property "Manufacturer_Name" "STMicroelectronics")
    (property "Manufacturer_Part_Number" "STL42P6LLF6")
    (property "Description" "STMicroelectronics STL42P6LLF6 P-channel MOSFET Transistor, 42 A, -60 V, 8-Pin PowerFLAT")
    (property "Datasheet_Link" "https://www.st.com/resource/en/datasheet/stl42p6llf6.pdf")
    (property "symbolName1" "STL42P6LLF6")
)
