(part "87427-0402"
    (packageRef "87427-04YY_347202")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "3") (portType INOUT))
        (port "4" (symbPinId 4) (portName "4") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "181")
    (property "Mouser_Part_Number" "538-87427-0402")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Molex/87427-0402?qs=BpFtYU5tmpvCqnqQ9%2FJ56w%3D%3D")
    (property "Manufacturer_Name" "Molex")
    (property "Manufacturer_Part_Number" "87427-0402")
    (property "Description" "Mini-Fit Jr. Header, 4.20mm Pitch, Right-Angle, without Flange, 4 Circuits")
    (property "Datasheet_Link" "https://www.molex.com/pdm_docs/sd/874270202_sd.pdf")
    (property "symbolName1" "87427-0402")
)
