(part "MPX1D1264L1R0"
    (packageRef "INDPM132125X640N")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "33")
    (property "Mouser_Part_Number" "80-MPX1D1264L1R0")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/KEMET/MPX1D1264L1R0?qs=P1JMDcb91o5Wago5y8gjMA%3D%3D")
    (property "Manufacturer_Name" "Yageo Group")
    (property "Manufacturer_Part_Number" "MPX1D1264L1R0")
    (property "Description" "Surface Mount Inductor")
    (property "Datasheet_Link" "https://www.yageogroup.com/content/datasheet/asset/file/KEM_L9012_MPX")
    (property "symbolName1" "MPX1D1264L1R0")
)
