(part "501568-0207"
    (packageRef "5015680207")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
        (port "MP1" (symbPinId 3) (portName "MP1") (portType INOUT))
        (port "MP2" (symbPinId 4) (portName "MP2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "181")
    (property "Mouser_Part_Number" "538-501568-0207")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Molex/501568-0207?qs=uEWtSLL707WbFjnit2JOEg%3D%3D")
    (property "Manufacturer_Name" "Molex")
    (property "Manufacturer_Part_Number" "501568-0207")
    (property "Description" "Molex PICO-CLASP Series, Series Number 501568, 1mm Pitch 2 Way 2 Row Right Angle PCB Header, Solder Termination, 1A")
    (property "Datasheet_Link" "https://www.molex.com/pdm_docs/sd/5015680207_sd.pdf")
    (property "symbolName1" "501568-0207")
)
