(part "202396-0207"
    (packageRef "2023960207")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
        (port "MP1" (symbPinId 3) (portName "MP1") (portType INOUT))
        (port "MP2" (symbPinId 4) (portName "MP2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "181")
    (property "Mouser_Part_Number" "538-202396-0207")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Molex/202396-0207?qs=5aG0NVq1C4yNVNVdbFIdrw%3D%3D")
    (property "Manufacturer_Name" "Molex")
    (property "Manufacturer_Part_Number" "202396-0207")
    (property "Description" "Headers & Wire Housings 1mm PicoClasp SMT SR 2CKT RA HDR GLD PTL")
    (property "Datasheet_Link" "https://www.molex.com/pdm_docs/sd/2023960207_sd.pdf")
    (property "symbolName1" "202396-0207")
)
