(part "AP22653AFDZ-7"
    (packageRef "SON65P200X200X80-7N")
    (interface
        (port "1" (symbPinId 1) (portName "OUT") (portType INOUT))
        (port "2" (symbPinId 2) (portName "ILIM") (portType INOUT))
        (port "3" (symbPinId 3) (portName "%FAULT%") (portType INOUT))
        (port "4" (symbPinId 4) (portName "EN") (portType INOUT))
        (port "5" (symbPinId 5) (portName "GND") (portType INOUT))
        (port "6" (symbPinId 6) (portName "IN") (portType INOUT))
        (port "7" (symbPinId 7) (portName "EP") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "621-AP22653AFDZ-7")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Diodes-Incorporated/AP22653AFDZ-7?qs=W%2FMpXkg%252BdQ5j0cis9bApsQ%3D%3D")
    (property "Manufacturer_Name" "Diodes Incorporated")
    (property "Manufacturer_Part_Number" "AP22653AFDZ-7")
    (property "Description" "Power Switch ICs - Power Distribution Load Switch W-DFN2020-6 T&R 3K")
    (property "Datasheet_Link" "https://www.diodes.com//assets/Datasheets/AP22652_53_52A_53A.pdf")
    (property "symbolName1" "AP22653AFDZ-7")
)
