(part "FAN3227TMX"
    (packageRef "SOIC127P600X175-8N")
    (interface
        (port "1" (symbPinId 1) (portName "ENA") (portType INOUT))
        (port "2" (symbPinId 2) (portName "INA") (portType INOUT))
        (port "3" (symbPinId 3) (portName "GND") (portType INOUT))
        (port "4" (symbPinId 4) (portName "INB") (portType INOUT))
        (port "5" (symbPinId 5) (portName "OUTB") (portType INOUT))
        (port "6" (symbPinId 6) (portName "VDD") (portType INOUT))
        (port "7" (symbPinId 7) (portName "OUTA") (portType INOUT))
        (port "8" (symbPinId 8) (portName "ENB") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "512-FAN3227TMX")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/onsemi-Fairchild/FAN3227TMX?qs=ODlIKnK5hgdsmwIkcdhHGg%3D%3D")
    (property "Manufacturer_Name" "onsemi")
    (property "Manufacturer_Part_Number" "FAN3227TMX")
    (property "Description" "Four Versions of Dual Independent Drivers: ; 3A Peak Sink/Source at VDD = 12V ; Dual Inverting + Enable (FAN3226) ; Typical Propagation Delay Under 20ns Matched within 1ns to the Other Channel ; 4.5 to 18V Operating Range ; 8-Lead 3x3mm MLP or 8-Lead SOIC Package ; Dual Non-Inverting + Enable (FAN3227) ; Dual-Inputs in Two Pin-Out Configurations:  Compatible with FAN3225x (FAN3228)  Compatible with TPS2814D (FAN3229) ; MillerDrive Technology ; 12ns / 9ns Typical Rise/Fall Times with 1nF Load ; Intern")
    (property "Datasheet_Link" "https://www.onsemi.com/pub/Collateral/FAN3229T-D.PDF")
    (property "symbolName1" "FAN3227TMX")
)
