(part "0157010_DR"
    (packageRef "0157010DR")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Mouser_Part_Number" "576-0157010.DR")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Littelfuse/0157010.DR?qs=n5MbhIql%252BRk%252BdkayiTTIMg%3D%3D")
    (property "Manufacturer_Name" "LITTELFUSE")
    (property "Manufacturer_Part_Number" "0157010.DR")
    (property "Description" "Littelfuse 10A FF Non-Resettable Surface Mount Fuse, 125V")
    (property "Datasheet_Link" "https://m.littelfuse.com/~/media/electronics/datasheets/fuses/littelfuse_fuse_157_datasheet.pdf.pdf")
    (property "symbolName1" "0157010_DR")
)
