(part "TPS25221DRVR"
    (packageRef "SON65P200X200X80-7N")
    (interface
        (port "1" (symbPinId 1) (portName "OUT") (portType INOUT))
        (port "2" (symbPinId 2) (portName "ILIM") (portType INOUT))
        (port "3" (symbPinId 3) (portName "%FAULT%") (portType INOUT))
        (port "4" (symbPinId 4) (portName "EN") (portType INOUT))
        (port "5" (symbPinId 5) (portName "GND") (portType INOUT))
        (port "6" (symbPinId 6) (portName "IN") (portType INOUT))
        (port "7" (symbPinId 7) (portName "EP") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "595-TPS25221DRVR")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Texas-Instruments/TPS25221DRVR?qs=y6ZabgHbY%252BwMfKdJX5xA9w%3D%3D")
    (property "Manufacturer_Name" "Texas Instruments")
    (property "Manufacturer_Part_Number" "TPS25221DRVR")
    (property "Description" "Precision Adjustable Current-Limited Power-Distribution Switches")
    (property "Datasheet_Link" "http://www.ti.com/lit/gpn/TPS25221")
    (property "symbolName1" "TPS25221DRVR")
)
