(part "APTF1616LSEKJ3ZGKQBC"
    (packageRef "APTF1616LSEKJ3ZGKQBC")
    (interface
        (port "1" (symbPinId 1) (portName "COMMON_CATHODE") (portType INOUT))
        (port "2" (symbPinId 2) (portName "ANODE_1") (portType INOUT))
        (port "3" (symbPinId 3) (portName "ANODE_2") (portType INOUT))
        (port "4" (symbPinId 4) (portName "ANODE_3") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "122")
    (property "Mouser_Part_Number" "604-APTF1616LSEKJ3ZG")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Kingbright/APTF1616LSEKJ3ZGKQBC?qs=ZqXcJfGlKsilY2K6EwZ11Q%3D%3D")
    (property "Manufacturer_Name" "Kingbright")
    (property "Manufacturer_Part_Number" "APTF1616LSEKJ3ZGKQBC")
    (property "Description" "Red, Green, Blue (RGB) 625nm Red, 525nm Green, 465nm Blue LED Indication - Discrete 1.8V Red, 2.7V Green, 2.7V Blue 0606 (1616 Metric)")
    (property "Datasheet_Link" "https://componentsearchengine.com/Datasheets/1/APTF1616LSEKJ3ZGKQBC.pdf")
    (property "symbolName1" "APTF1616LSEKJ3ZGKQBC")
)
