(part "STL36DN6F7"
    (packageRef "STL36DN6F7")
    (interface
        (port "1" (symbPinId 1) (portName "S2") (portType INOUT))
        (port "2" (symbPinId 2) (portName "G2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "S1") (portType INOUT))
        (port "4" (symbPinId 4) (portName "G1") (portType INOUT))
        (port "5" (symbPinId 5) (portName "D1_1") (portType INOUT))
        (port "6" (symbPinId 6) (portName "D1_2") (portType INOUT))
        (port "7" (symbPinId 7) (portName "D2_1") (portType INOUT))
        (port "8" (symbPinId 8) (portName "D2_2") (portType INOUT))
        (port "9" (symbPinId 9) (portName "D2_3") (portType INOUT))
        (port "10" (symbPinId 10) (portName "D1_3") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Mouser_Part_Number" "511-STL36DN6F7")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/STMicroelectronics/STL36DN6F7/?qs=u4fy%2FsgLU9MwLM2KeqBprA%3D%3D")
    (property "Manufacturer_Name" "STMicroelectronics")
    (property "Manufacturer_Part_Number" "STL36DN6F7")
    (property "Description" "Dual N-channel 60 V, 23 m typ., 33 A STripFET F7 Power MOSFET in a PowerFLAT 5x6 double island package")
    (property "Datasheet_Link" "https://www.st.com/resource/en/datasheet/stl36dn6f7.pdf")
    (property "symbolName1" "STL36DN6F7")
)
