(part "USB1130-15-A"
    (packageRef "USB113015A")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "3") (portType INOUT))
        (port "4" (symbPinId 4) (portName "4") (portType INOUT))
        (port "5" (symbPinId 5) (portName "MH1") (portType INOUT))
        (port "6" (symbPinId 6) (portName "MH2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "181")
    (property "Mouser_Part_Number" "640-USB1130-15-A")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/GCT/USB1130-15-A?qs=KUoIvG%2F9IlbUm2WMV7vmzg%3D%3D")
    (property "Manufacturer_Name" "GCT (GLOBAL CONNECTOR TECHNOLOGY)")
    (property "Manufacturer_Part_Number" "USB1130-15-A")
    (property "Description" "USB Connectors USB A 2.0 Skt RA High Life 15u" T Hole W/Shell Stake T & R")
    (property "Datasheet_Link" "https://gct.co/files/drawings/usb1130.pdf?v=af75e0ab-3313-4c97-a925-9953a1c7de6b")
    (property "symbolName1" "USB1130-15-A")
)
