(part "STL8N10F7"
    (packageRef "STL8N10F7")
    (interface
        (port "1" (symbPinId 1) (portName "S_1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "S_2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "S_3") (portType INOUT))
        (port "4" (symbPinId 4) (portName "G") (portType INOUT))
        (port "5" (symbPinId 5) (portName "D_1") (portType INOUT))
        (port "6" (symbPinId 6) (portName "D_2") (portType INOUT))
        (port "7" (symbPinId 7) (portName "D_3") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Mouser_Part_Number" "511-STL8N10F7")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/STMicroelectronics/STL8N10F7?qs=DqCdCwOw4%2F4Qzkp1A1E6dA%3D%3D")
    (property "Manufacturer_Name" "STMicroelectronics")
    (property "Manufacturer_Part_Number" "STL8N10F7")
    (property "Description" "N-channel 100 V, 17 m typ., 8 A STripFET F7 Power MOSFET in a PowerFLAT 3.3x3.3 package")
    (property "Datasheet_Link" "https://www.st.com/resource/en/datasheet/stl8n10f7.pdf")
    (property "symbolName1" "STL8N10F7")
)
